#!/usr/bin/env bash
#configuration file for a simple server

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo chmod a+w /var/www/html/index.nginx-devian.html
echo "Holberton School" > /var/www/html/index.nginx-devian.html
sudo service nginx restart
