#!/usr/bin/env bash
#configuration file for a simple server

sudo apt-get update
sudo apt-get upgrade
sudo apt-get -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
