#!/usr/bin/env bash
#configuration file for a simple server

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo chmod a+w /var/www/html/index.nginx-debian.html
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
