#!/usr/bin/env bash
# you need to configure web-02 to be identical to web-01
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get install -y nginx
sudo ufw allow "Nginx HTTP"
sudo sed -i "21 i\\\add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
