#!/usr/bin/env bash
# you need to configure web-02 to be identical to web-01
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get install -y nginx
sudo ufw allow "Nginx HTTP"
sudo sed -i "21 i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart
