#!/usr/bin/env bash
#Configure the loas balancer

sudo apt-get install -y haproxy
sudo sed -i "$ a\\\nfrontend firstbalance\n\tbind *:80\n\toption forwardfor\n\t
default_backend webservers" /etc/haproxy/haproxy.cfg
sudo sed -i "$ a\\\nbackend webservers\n\tbalance roundrobin\n\t
server webserver1 35.237.144.175:80\n\tserver webserver2 35.237.121.43:80\n\t
server webserver1 35.237.144.175:80 check\n\tserver webserver2 35.237.121.43:80
check\n\toption httpchk" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
