#!/usr/bin/env bash
#Write a Bash script that displays the time for 12 hours and 59 minutes:
#display hours from 0 to 12
#display minutes from 1 to 59

min=0
hrs=0
while [ "$hrs" -lt 13 ]
do
    echo "Hour: $hrs"
    min=1
    while [ "$min" -lt 60 ]; do
	echo "$min"
	let min=min+1
    done
    let hrs=hrs+1
done
