#!/usr/bin/env bash
#configure firewall
sudo ufw disable
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo sed -i '/*filter/i \n
*nat\n
:PREROUTING ACCEPT [0:0]\n
-A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80\n
COMMIT\n' /etc/ufw/before.rules
sudo ufw enable
