#!/usr/bin/env bash
#script to create a server with a non root user named nginx
pkill -f apache2
sed -i 's/listen 80 default_server;/listen 8080 default_server;/g' /etc/nginx/sites-available/default
sudo sed -i 's/listen \[\:\:\]\:80 default_server ipv6only\=on;/listen [::]:8080 default_server ipv6only=on;/g' /etc/nginx/sites-available/default
sudo sed -i 's/#user www-data/user nginx/g' /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
