#!/usr/bin/env bash
#script to create a server with a non root user named nginx
pkill -f apache2
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sed -i 's/80 default_server;/8080 default_server;/g' /etc/nginx/sites-available/default
sed -i 's/#user www-data/user nginx/g' /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
